name: deploy web to production server

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chechout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build
      
    - name: deploy to server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
       DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
       ARGS: "-e -c -r --delete"
       SERVER_PORT: ${{ secrets.SERVER_PORT }}
       FOLDER: "./dist/*"
       SERVER_IP: ${{ secrets.SERVER_IP }}
       USERNAME: ${{ secrets.USERNAME }}
       SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
